### ISSUE TITLE
ready-made costume designs that are not completed

### ISSUE THREAD

**Issue by icefreesky** [CanavarB/MOCAP#1]
https://github.com/herzig/bewegungsfelder
it has a problem with rotation along the z axis, but if you add an electronic compass that shows north, you can remove the rotation, simply using the gy-87 mpu6050 + HMC5883L sensor, you get an analogue of mpu9250
https://github.com/kharlashkin/MPU-9250DMP
this is a working code with a compass but only under 9250 it uses 9 axes and there is no drift but these sensors can no longer be bought they are out of production and only fakes on aliexpress
https://github.com/ArunmozhiRajavel/ESP_MotionCapture
in this project there is no blend file with code and there are only 6 axes here, but it works on esp
https://github.com/T-K-233/Dual-MPU6050-Motion-Sync

**Comment by icefreesky** [comment]
https://github.com/mjs513/FreeIMU-Updates

**Comment by CanavarB** [comment]
I saw what you wrote from the first moment, but I can't make those adjustments right now because I disassembled them all. This is a project presentation for my portfolio. In the first project, the directions were correct, but there was no proper code writing. If there is something you want to fix, you can send a pull request. Necessary fixing can be done from: https://github.com/CanavarB/MOCAP/blob/master/UPBGE/bone.py#L13 . You can multiply those matrix with the corrections vector which passed from constructor (c_vec).
