### ISSUE TITLE
please contact me i will send you premad esp-mpu

### ISSUE THREAD

**Issue by EkaHum** [CanavarB/MOCAP#2]
please contact me ,
i have premde esp32+mpu6050 set, 
5 of them with strip could fix on your leg. wist chest and so on.

which will make you faster on coding.

**Comment by EkaHum** [comment]
anyone instrested in develop simlar program also could contact for free hardware

**Comment by CanavarB** [comment]
> please contact me , i have premde esp32+mpu6050 set, 5 of them with strip could fix on your leg. wist chest and so on.
> 
> which will make you faster on coding.

I saw what you wrote from the first moment, but I can't make those adjustments right now because I disassembled them all. This is a project presentation for my portfolio. In the first project, the directions were correct, but there was no proper code writing. If there is something you want to fix, you can send a pull request. Necessary fixing can be done from: https://github.com/CanavarB/MOCAP/blob/master/UPBGE/bone.py#L13 . You can multiply those matrix with the corrections vector which passed from constructor (c_vec).
